### ISSUE TITLE
euler2quat order

### ISSUE THREAD

**Issue by yizhengzhang1** [MomsFriendlyRobotCompany/squaternion#1]
What is the rotation order of roll, pitch, yaw when using euler2quat function?

**Comment by walchko** [comment]
Hello! 

From the `readme`:

```python
# euler angles euler2quat(roll, pitch, yaw), default is radians, but set
# degrees true if giving degrees
q = euler2quat(0, -90, 100, degrees=True)
```

I should probably add it to the doc string too ... thanks!

**Comment by yizhengzhang1** [comment]
Cool! Please specifies the sequence of axes for rotations.

**Comment by walchko** [comment]
done
