### ISSUE TITLE
Fails to retrieve metadata when bundled via pyinstaller

### ISSUE THREAD

**Issue by hollowstrawberry** [MomsFriendlyRobotCompany/squaternion#3]
Hey. When you use pyinstaller to bundle a python script that imports this package, a `PackageNotFoundError` is raised at runtime on `__version__ = version("squaternion")` in `__init__.py`.

This is because importlib can't retrieve the metadata when it's bundled as a frozen package.

Could you fix it? The simplest way would be to just replace that line with `__version__ = "0.3.1"`.

If not, do you know how I could fix this without manually editing your package in my site-packages?

**Comment by walchko** [comment]
So I use `pyproject.toml` to keep track of my version number and I hate having to track the version in 2 places. I do this on all of my packages. I am not familiar with pyinstaller and I don't know why `importlib-metadata` doesn't work correctly ... maybe it is an issue with `importlib-metadata`, have you filed an issue with them? Also, `importlib-metadata` is a backport of the python 3.8 `importlib`, so maybe somehow the backport is not getting installed if you are using a python version before 3.8? 

My setup works for the standard install process on both macOS and Linux, so I don't think I am doing anything wrong on my side. Maybe there is something you can do on the pyinstaller side to fix your issue?

**Comment by hollowstrawberry** [comment]
I'll take another look at what I can do on my end and I'll fill an issue on importlib/pyinstaller if necessary (it had been discussed in the past, but it seems it's still an issue). Thanks for the response!

**Comment by runette** [comment]
Just a note that this still seems to be a problem but I fixed it in my pyinstaller `.spec` file by :

1 add this to the imports
`from PyInstaller.utils.hooks import copy_metadata`

2 add this after the `datas` variable is initialised
`datas.extend(copy_metadata('squaternion'))`
