### ISSUE TITLE
The different results given by squaternion and https://quaternions.online/ when converting Euler angles to Quaternion representation.

### ISSUE THREAD

**Issue by hongyi-zhao** [MomsFriendlyRobotCompany/squaternion#5]
Hi,

I try to convert between Euler and Quaternion representations. But I obtained different results when using squaternion and [the online converter](https://quaternions.online/). See following for detailed info:

The results obtained from squaternion:
```
In [1]: from squaternion import Quaternion                                                 
In [12]: q = Quaternion.from_euler(30, 30, 60, degrees=True)                               

In [13]: q                                                                                 
Out[13]: Quaternion(w=0.8415063509461097, x=0.0915063509461097, y=0.3415063509461096, z=0.40849364905389035)
```
 The results given by [the online converter](https://quaternions.online/):

![image](https://user-images.githubusercontent.com/11155854/97302339-e1a6db80-1893-11eb-8be7-d3ebce32ef12.png)

Any hints for this problem?

Regards,
HY

**Comment by walchko** [comment]
So quaternions are  a 4D representation of a 3D world, there is not a unique solution. You also see this in Euler angles, there are many representations, some common ones being 123, 313, 321, etc. Now, choices are made when you transform from quaternion to Euler or Euler to quaternion. I chose what wikipedia says to do :smile:, so if you look at the code in my git repo, I cite where I got everything from. Whatever the viewer you are using is, I don't know what choices they made.

**Comment by hongyi-zhao** [comment]
The problem is: are all of these different solutions equivalent?

**Comment by hongyi-zhao** [comment]
I do some further exploration on this problem and find the reason. See my following descriptions for more detailed explanations.

I later try the conversion with the *scipy* and *squaternion* respcectively. The [from_euler classmethod](https://github.com/scipy/scipy/blob/fc4a0e862169481a962900dc5e0bfed243906e33/scipy/spatial/transform/rotation.pyx#L866) in the Rotation module of scipy.spatial.transform class supports the following option:

```
        The three rotations can either be in a global frame of reference
        (extrinsic) or in a body centred frame of reference (intrinsic), which
        is attached to, and moves with, the object under rotation
        [snipped]
        seq : string
            Specifies sequence of axes for rotations. Up to 3 characters
            belonging to the set {'X', 'Y', 'Z'} for intrinsic rotations, or
            {'x', 'y', 'z'} for extrinsic rotations. Extrinsic and intrinsic
            rotations cannot be mixed in one function call.
```

I write the following code for testing the conversion of Euler angles to Quaternion representation:

```
from scipy.spatial.transform import Rotation as R
from squaternion import Quaternion

q = Quaternion.from_euler(30, 30, 60, degrees=True)

extrinsic_r = R.from_euler('xyz', [30, 30, 60], degrees=True)
intrinsic_r = R.from_euler('XYZ', [30, 30, 60], degrees=True)

extrinsic_quat = extrinsic_r.as_quat()
intrinsic_quat = intrinsic_r.as_quat()

sq_quat = []
sq_quat.extend([q.w, q.x, q.y, q.z])

ex_quat = [extrinsic_quat[3]]
ex_quat.extend(extrinsic_quat[:3])

in_quat = [intrinsic_quat[3]]
in_quat.extend(intrinsic_quat[:3])


print(sq_quat)
print(ex_quat)
print(in_quat)
```

The above code will give the results as following:

```
[0.8415063509461097, 0.0915063509461097, 0.3415063509461096, 0.40849364905389035]
[0.8415063509461097, 0.09150635094610968, 0.3415063509461096, 0.40849364905389035]
[0.7745190528383291, 0.3415063509461096, 0.09150635094610968, 0.524519052838329]
```

So it is obvious that the squaternion's result is obtained in a global frame of reference (extrinsic), while the one given by  [the quaternions.online](https://quaternions.online/) is calculated in a body centred frame of reference (intrinsic).

Regards,
HY

**Comment by walchko** [comment]
Good work! I am glad you were able to identify why there were different answers. I will probably update the documentation to clarify better. Thanks!

**Comment by hongyi-zhao** [comment]
But I find another question I still can't figure out. See following for more info.

When I try another online quaternion conversion tool located [here](https://www.onlineconversion.com/quaternions.htm), the result is different from the ones obtained by any of the methods mentioned above.

You can try it for yourself to verify what I've described.
